#! /bin/bash
#
# packer.sh
#
# Copyleft (ↄ) 2021 jkirchartz <me@jkirchartz.com>
#
# Distributed under terms of the NPL (Necessary Public License) license.
#

shopt -s extglob

function add {
  git submodule add "$1" "pack/plugins/$2/${1//+(*\/|.*)}" $3
}

function remove {
  git rm $1
}

function update {
  git submodule update --init --recursive --remote
}

case $1 in
  add)
    add "$2" "${3:-start}" "${@:3}";
    update;
    ;;
  remove)
    git submodule deinit "${@:2}" --force
    git rm "${@:2}" --force
    update
    ;;
  update) update;;
  help|*)
    echo 'pk add <git repo for plugin> [pack directory (defaults to start)]';
    echo 'pk remove pack/plugins/<directory>/<plugin>';
    echo 'update';
    ;;
esac
